/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurant1;

import java.awt.*;

import javax.swing.*;

/**
 *
 * @author DELL
 */
public class Restaurant1 extends javax.swing.JFrame {
JProgressBar jb;
    JProgressBar jb1;
    
    int i=0;   
    JFrame j;
    JPanel jp;
    private Object m;
    static String dbURL = "jdbc:mysql://localhost:3306/Restaurant";
    static String username = "root";
    static String password ="12346789";
    
    public Restaurant1() {
        //initComponents();
        JLabel jl = new JLabel("Welcome to Maverick Restaurant");
        
        j = new JFrame("Maverick Restaurant");
        jb=new JProgressBar(0,100);

        jl.setBounds(300,400,1500,100);
        jl.setFont(new Font("", Font.PLAIN, 100));
        jl.setForeground(Color.blue);
        jb.setBounds(300,600,1500,70);         
        jb.setValue(0);    
        jb.setStringPainted(true); 
        //jb.setBackground(Color.BLUE);
        
        JLabel Background;
        
        ImageIcon icon = new ImageIcon("C:\\Users\\DELL\\Desktop\\north-indian-cuisine.jpg");
      Background = new JLabel("",icon,JLabel.CENTER);
      Background.setBounds(-10, -10, 1920,1080);
        
        
        add(Background);
        Background.add(jl);
        Background.add(jb);
        //jl.setAlignmentX(Centre);

        jb.setVisible(true);
        Background.setVisible(true);
        Background.setLayout(null);
        
        
        setSize(1920,1080);   
        
        setLayout(null); 
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    
    private void ProgressBar() {
        while(i<=100){    
            jb.setValue(i);    
            i=i+10;    
            try{Thread.sleep(150);}catch(Exception e){}    
        }//To change body of generated methods, choose Tools | Templates.
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurant1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurant1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurant1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurant1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
   
        //</editor-fold>
        Restaurant1 m;  
        m = new Restaurant1();
        m.setVisible(true);   
        m.ProgressBar();
        m.ProgressBar();
        //m.setBackground(Color.BLACK);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                //
                new jb();
                
            }
        });
        
    }

    // Variables declaration - do not modify                     
   
    // End of variables declaration                   
}
